import dayjs from 'dayjs';
import { v1 } from 'uuid';
import { ICalendarEvents } from 'pages/CalendarPage/CalendarPage';
import { OrganizationTypes } from 'enums';

interface IKpi {
  plan: number;
  fact: number;
  still: number;
  planCompletion: number;
}

interface IVisitingChartData {
  id: string;
  date: string;
  responsible: string;
  medicine: string;
  potential: string;
  loyalty: string;
  objections: string;
  detailing: boolean;
}

interface IDrug {
  id: string;
  drug: string;
}

export interface IVisitDescriptionCard {
  id: string;
  number: number;
  date: Date;
  title: string;
}

export interface IFakeContact {
  id: string;
  fullName: string;
  company: string;
  phone: string;
  position: string;
  type: OrganizationTypes;
  address: string;
  email: string;
}

export interface IFakeTarget {
  id: string;
  fullName: string;
  company: string;
  phone: string;
  position: string;
  type: OrganizationTypes;
  address: string;
  email: string;
  visitsPlanned: number;
  visitsPerformed: number;
}

export const calendarEventsTodayPageData: ICalendarEvents[] = [
  {
    id: v1(),
    title: 'Совместный визит',
    start: dayjs('2023-02-04 08:00', 'HH:mm').toDate(),
    end: dayjs('2023-02-04 08:00', 'HH:mm').add(1, 'hours').toDate(),
    color: '#6438E0',
  },
  {
    id: v1(),
    title: 'Совместный визит',
    start: dayjs('2023-02-04 09:00', 'HH:mm').toDate(),
    end: dayjs('2023-02-04 09:00', 'HH:mm').add(1, 'hours').toDate(),
    color: '#BE1A1A',
  },
  {
    id: v1(),
    title: 'Визит в аптеку',
    start: dayjs('2023-02-04 10:00', 'HH:mm').toDate(),
    end: dayjs('2023-02-04 10:00', 'HH:mm').add(1, 'hours').toDate(),
    color: '#E7C160',
  },
  {
    id: v1(),
    title: 'Встреча с врачом',
    start: dayjs('2023-02-04 11:00', 'HH:mm').toDate(),
    end: dayjs('2023-02-04 11:00', 'HH:mm').add(1, 'hours').toDate(),
    color: '#55D28F',
  },
  {
    id: v1(),
    title: 'Встреча с врачом',
    start: dayjs('2023-02-04 12:00', 'HH:mm').toDate(),
    end: dayjs('2023-02-04 12:00', 'HH:mm').add(1, 'hours').toDate(),
    color: '#8FDCB2',
  },
];

export const calendarEventsTomorrowPageData: ICalendarEvents[] = [
  {
    id: v1(),
    title: 'Встреча с врачом',
    start: dayjs('2023-02-09 13:00', 'HH:mm').toDate(),
    end: dayjs('2023-02-09 13:00', 'HH:mm').add(1, 'hour').toDate(),
    color: '#8FDCB2',
  },
  {
    id: v1(),
    title: 'Совместный визит',
    start: dayjs('2023-02-09 14:00', 'HH:mm').toDate(),
    end: dayjs('2023-02-09 14:00', 'HH:mm').add(1, 'hours').toDate(),
    color: '#A384FF',
  },
  {
    id: v1(),
    title: 'Визит в аптеку',
    start: dayjs('2023-02-09 15:00', 'HH:mm').toDate(),
    end: dayjs('2023-02-09 15:00', 'HH:mm').add(1, 'hours').toDate(),
    color: '#DEB373',
  },
];

export const kpiData: IKpi[] = [
  {
    plan: 50,
    fact: 30,
    still: 20,
    planCompletion: 60,
  },
  {
    plan: 220,
    fact: 120,
    still: 100,
    planCompletion: 55,
  },
  {
    plan: 660,
    fact: 360,
    still: 300,
    planCompletion: 55,
  },
];

export const contactsPageDate: IFakeContact[] = [
  {
    id: v1(),
    fullName: 'Глушаков Денис Борисович',
    company: 'ГБУЗ РКПЦ МЗ РБ',
    phone: '8 (999) 049-20-67',
    position: 'Ультразвуковая диагностика',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'lubov851@mail.ru',
  },
  {
    id: v1(),
    fullName: 'Горлукович Сергей Вадимович',
    company: 'ГБУЗ РБ РД № 3 Г.УФА',
    phone: '8 (999) 914-52-29',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'shayakhmetoff.artur@yandex.ru',
  },
  {
    id: v1(),
    fullName: 'Дзагоев Алан Елизбарович',
    company: 'ГБУЗ РБ РД № 3 Г.УФА',
    phone: '8 (999) 760-63-26',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'mans.lily@yandex.ru',
  },
  {
    id: v1(),
    fullName: 'Енин Артём Валерьевич',
    company: 'ООО "ИНС ОКБМ"',
    phone: '8 (999) 420-99-25',
    position: 'Гематология',
    type: OrganizationTypes.MPI,
    address: 'Воронеж',
    email: 'uriimaltsev@mail.ru',
  },
  {
    id: v1(),
    fullName: 'Зубко Денис Иванович',
    company: 'КГБУЗ "БОГОТОЛЬСКАЯ МБ"',
    phone: '8 (999) 592-13-78',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.MPI,
    address: 'Боготол',
    email: 'arisa275@yandex.ru',
  },
  {
    id: v1(),
    fullName: 'Каряка Андрей Константинович',
    company: 'Альфа центр Здоровья',
    phone: '8 (999) 492-33-24',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.MPI,
    address: 'Тюмень',
    email: 'nadyusha@live.rubykolaki',
  },
  {
    id: v1(),
    fullName: 'Кобелев Андрей Николаевич',
    company: 'ГБУЗ РБ ГКБ № 21 Г. УФА',
    phone: '8 (999) 437-69-40',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'gerbveronika@gmail.com',
  },
  {
    id: v1(),
    fullName: 'Кондрашов Андрей Юрьевич',
    company: 'ГБУЗ РБ ГКБ № 21 Г. УФА',
    phone: '8 (999) 444-89-03',
    position: 'Гинекология',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'otro227@mail.ru',
  },
  {
    id: v1(),
    fullName: 'Кузнецов Дмитрий Викторович',
    company: 'ГБУЗ РКБ ИМ. Г.Г.КУВАТОВА',
    phone: '8 (999) 336-41-25',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'shahmatka1990@mail.ru',
  },
  {
    id: v1(),
    fullName: 'Ледяхов Игорь Анатольевич',
    company: 'МУП ХП Г. УФЫ',
    phone: '8 (999) 156-39-93',
    position: 'Гинекология',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'g-bik@list.ru',
  },
  {
    id: v1(),
    fullName: 'Мамедов Рамиз Михманович',
    company: 'СПБ ГКУЗ',
    phone: '8 (999) 268-96-45',
    position: 'Гинекология',
    type: OrganizationTypes.MPI,
    address: 'Санкт-Петербург',
    email: 'nasoge@mail.ru',
  },
  {
    id: v1(),
    fullName: 'Миранчук Алексей Андреевич',
    company: 'ГБУЗ РБ ПОЛИКЛИНИКА № 46 Г.УФА',
    phone: '8 (999) 492-83-08',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'bagdasaryan1988@mail.ru',
  },
  {
    id: v1(),
    fullName: 'Подпалый Сергей Иванович',
    company: 'МЦ АРМЕД',
    phone: '8 (999) 957-99-45',
    position: 'Отоларингология',
    type: OrganizationTypes.MPI,
    address: 'Сочи',
    email: 'mywaydao@rambler.ru',
  },
  {
    id: v1(),
    fullName: 'Беклемишев Иван Никитич',
    company: '36,6',
    phone: '8 (999) 623-99-45',
    position: 'Провизор',
    type: OrganizationTypes.PHARMACY,
    address: 'Москва',
    email: 'mannu.ch@gmail.com',
  },
  {
    id: v1(),
    fullName: 'Поджогин Василий Юрьевич',
    company: 'Ригла',
    phone: '8 (999) 123-99-09',
    position: 'Провизор',
    type: OrganizationTypes.PHARMACY,
    address: 'Москва',
    email: 'hero2231@gmail.com',
  },
  {
    id: v1(),
    fullName: 'Загряжский Даниил Дмитриевич',
    company: 'Implozia',
    phone: '8 (999) 983-99-01',
    position: 'Провизор',
    type: OrganizationTypes.PHARMACY,
    address: 'Москва',
    email: 'karanboka@gmail.com',
  },
  {
    id: v1(),
    fullName: 'Милославский Фёдор Яковлевич',
    company: 'Планета здоровья',
    phone: '8 (999) 643-99-34',
    position: 'Провизор',
    type: OrganizationTypes.PHARMACY,
    address: 'Москва',
    email: 'bokachoodatui@gmail.com',
  },
  {
    id: v1(),
    fullName: 'Нагой Афанасий Фёдорович',
    company: 'Самсон Фарма',
    phone: '8 (999) 421-99-21',
    position: 'Провизор',
    type: OrganizationTypes.PHARMACY,
    address: 'Москва',
    email: 'chaloca-le@yahoo.com',
  },
  {
    id: v1(),
    fullName: 'Степанов Василий Васильевич',
    company: 'АПТЕКА ДОКТОР',
    phone: '8 (999) 333-99-33',
    position: 'Провизор',
    type: OrganizationTypes.PHARMACY,
    address: 'Санкт-Петербург',
    email: 'jojo.okl1@yahoo.com',
  },
  {
    id: v1(),
    fullName: 'Заболоцкий Тимофей Васильевич',
    company: 'ЭРКАФАРМ',
    phone: '8 (999) 492-99-11',
    position: 'Провизор',
    type: OrganizationTypes.PHARMACY,
    address: 'Санкт-Петербург',
    email: 'amit234@yahoo.com',
  },
  {
    id: v1(),
    fullName: 'Болотников Иван Иванович',
    company: 'АПТЕЧНАЯ СЕТЬ 03',
    phone: '8 (999) 552-99-45',
    position: 'Провизор',
    type: OrganizationTypes.PHARMACY,
    address: 'Санкт-Петербург',
    email: 'mr.das3@hotmail.com',
  },
  {
    id: v1(),
    fullName: 'Воронцов Фёдор Семёнович',
    company: 'Фармаимпекс',
    phone: '8 (999) 462-12-45',
    position: 'Провизор',
    type: OrganizationTypes.PHARMACY,
    address: 'Санкт-Петербург',
    email: 'deepani-2012@icloud.com',
  },
  {
    id: v1(),
    fullName: 'Гавренев Иван Афанасьевич',
    company: 'Будь Здоров!',
    phone: '8 (999) 442-22-45',
    position: 'Провизор',
    type: OrganizationTypes.PHARMACY,
    address: 'Санкт-Петербург',
    email: 'feedback@copanay.com',
  },
];

// export const companyPageDate: IOrganization[] = [
//   {
//     id: v1(),
//     name: 'ГБУЗ РКПЦ МЗ РБ 12',
//     numberOfEmployees: '126',
//     type: OrganizationTypes.MPI,
//     address: 'Уфа',
//   },
//   {
//     id: v1(),
//     name: 'ЗАО "ОКБ "ИВЭНЕРГОМАШ"',
//     numberOfEmployees: '23',
//     type: OrganizationTypes.MPI,
//     address: 'Иваново',
//   },
//   {
//     id: v1(),
//     name: 'ООО "ИНС ОКБМ"',
//     numberOfEmployees: '35',
//     type: OrganizationTypes.MPI,
//     address: 'Воронеж',
//   },
//   {
//     id: v1(),
//     name: 'ОГБУЗ ОБ КО №1',
//     numberOfEmployees: '45',
//     type: OrganizationTypes.MPI,
//     address: 'Кострома',
//   },
//   {
//     id: v1(),
//     name: 'ЧУЗ "КБ "РЖД-МЕДИЦИНА" ИМ.Н.А.СЕМАШКО"',
//     numberOfEmployees: '31',
//     type: OrganizationTypes.MPI,
//     address: 'Москва',
//   },
//   {
//     id: v1(),
//     name: 'ГБУЗ РБ РД № 3 Г.УФА',
//     numberOfEmployees: '23',
//     type: OrganizationTypes.MPI,
//     address: 'Уфа',
//   },
//   {
//     id: v1(),
//     name: 'ГБУЗ РБ ГКБ № 21 Г. УФА',
//     numberOfEmployees: '56',
//     type: OrganizationTypes.MPI,
//     address: 'Уфа',
//   },
//   {
//     id: v1(),
//     name: 'ГБУЗ РКБ ИМ. Г.Г.КУВАТОВА',
//     numberOfEmployees: '45',
//     type: OrganizationTypes.MPI,
//     address: 'Уфа',
//   },
//   {
//     id: v1(),
//     name: 'КГБУЗ "БОГОТОЛЬСКАЯ МБ"',
//     numberOfEmployees: '23',
//     type: OrganizationTypes.MPI,
//     address: 'Боготол',
//   },
//   {
//     id: v1(),
//     name: 'Сургутская районная поликлиника',
//     numberOfEmployees: '78',
//     type: OrganizationTypes.MPI,
//     address: 'Сургут',
//   },
//   {
//     id: v1(),
//     name: 'ГКБ № 1 ИМ. Н.И.ПИРОГОВА',
//     numberOfEmployees: '67',
//     type: OrganizationTypes.MPI,
//     address: 'Москва',
//   },
//   {
//     id: v1(),
//     name: 'МЦ АРМЕД',
//     numberOfEmployees: '23',
//     type: OrganizationTypes.PHARMACY,
//     address: 'Сочи',
//   },
//   {
//     id: v1(),
//     name: 'МУП ХП Г. УФЫ',
//     numberOfEmployees: '23',
//     type: OrganizationTypes.PHARMACY,
//     address: 'Уфа',
//   },
//   {
//     id: v1(),
//     name: 'МУП ХП Г. УФЫ',
//     numberOfEmployees: '23',
//     type: OrganizationTypes.PHARMACY,
//     address: 'Уфа',
//   },
//   {
//     id: v1(),
//     name: 'ГБУЗ РБ ПОЛИКЛИНИКА № 46',
//     numberOfEmployees: '78',
//     type: OrganizationTypes.MPI,
//     address: 'Уфа',
//   },
//   {
//     id: v1(),
//     name: 'Альфа центр Здоровья',
//     numberOfEmployees: '12',
//     type: OrganizationTypes.PHARMACY,
//     address: 'Тюмень',
//   },
//   {
//     id: v1(),
//     name: 'ВОДЦ',
//     numberOfEmployees: '23',
//     type: OrganizationTypes.MPI,
//     address: 'Витебск',
//   },
//   {
//     id: v1(),
//     name: 'ФГКУ ПОЛИКЛИНИКА № 6',
//     numberOfEmployees: '34',
//     type: OrganizationTypes.MPI,
//     address: 'Москва',
//   },
//   {
//     id: v1(),
//     name: 'ГАУЗ ЧОДКБ',
//     numberOfEmployees: '45',
//     type: OrganizationTypes.MPI,
//     address: 'Челябинск',
//   },
//   {
//     id: v1(),
//     name: 'ГБУЗ СК',
//     numberOfEmployees: '12',
//     type: OrganizationTypes.PHARMACY,
//     address: 'Ставрополь',
//   },
//   {
//     id: v1(),
//     name: 'ГБУЗ',
//     numberOfEmployees: '323',
//     type: OrganizationTypes.MPI,
//     address: 'Москва',
//   },
//   {
//     id: v1(),
//     name: 'ГБУЗ РБ ГКБ №13 Г.УФА',
//     numberOfEmployees: '34',
//     type: OrganizationTypes.MPI,
//     address: 'Уфа',
//   },
//   {
//     id: v1(),
//     name: 'ФКУ "ЦВКГ ИМ. П.В.МАНДРЫКА',
//     numberOfEmployees: '54',
//     type: OrganizationTypes.MPI,
//     address: 'Москва',
//   },
//   {
//     id: v1(),
//     name: 'ГБУЗ ГКБ ИМ. С.П. БОТКИНА ДЗМ',
//     numberOfEmployees: '45',
//     type: OrganizationTypes.MPI,
//     address: 'Москва',
//   },
//   {
//     id: v1(),
//     name: 'ГБУЗ РБ ГКБ № 21 Г. УФА',
//     numberOfEmployees: '24',
//     type: OrganizationTypes.MPI,
//     address: 'Уфа',
//   },
// ];

export const targetsPageDate: IFakeTarget[] = [
  {
    id: v1(),
    fullName: 'Глушаков Денис Борисович',
    company: 'ГБУЗ РКПЦ МЗ РБ',
    phone: '8 (999) 049-20-67',
    position: 'Ультразвуковая диагностика',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'lubov851@mail.ru',
    visitsPlanned: 8,
    visitsPerformed: 2,
  },
  {
    id: v1(),
    fullName: 'Горлукович Сергей Вадимович',
    company: 'ГБУЗ РБ РД № 3 Г.УФА',
    phone: '8 (999) 914-52-29',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'shayakhmetoff.artur@yandex.ru',
    visitsPlanned: 5,
    visitsPerformed: 4,
  },
  {
    id: v1(),
    fullName: 'Дзагоев Алан Елизбарович',
    company: 'ГБУЗ РБ РД № 3 Г.УФА',
    phone: '8 (999) 760-63-26',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'mans.lily@yandex.ru',
    visitsPlanned: 9,
    visitsPerformed: 7,
  },
  {
    id: v1(),
    fullName: 'Енин Артём Валерьевич',
    company: 'ООО "ИНС ОКБМ"',
    phone: '8 (999) 420-99-25',
    position: 'Гематология',
    type: OrganizationTypes.PHARMACY,
    address: 'Воронеж',
    email: 'uriimaltsev@mail.ru',
    visitsPlanned: 5,
    visitsPerformed: 2,
  },
  {
    id: v1(),
    fullName: 'Зубко Денис Иванович',
    company: 'КГБУЗ "БОГОТОЛЬСКАЯ МБ"',
    phone: '8 (999) 592-13-78',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Боготол',
    email: 'arisa275@yandex.ru',
    visitsPlanned: 6,
    visitsPerformed: 4,
  },
  {
    id: v1(),
    fullName: 'Каряка Андрей Константинович',
    company: 'Альфа центр Здоровья',
    phone: '8 (999) 492-33-24',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Тюмень',
    email: 'nadyusha@live.rubykolaki',
    visitsPlanned: 5,
    visitsPerformed: 3,
  },
  {
    id: v1(),
    fullName: 'Кобелев Андрей Николаевич',
    company: 'ГБУЗ РБ ГКБ № 21 Г. УФА',
    phone: '8 (999) 437-69-40',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'gerbveronika@gmail.com',
    visitsPlanned: 3,
    visitsPerformed: 0,
  },
  {
    id: v1(),
    fullName: 'Кондрашов Андрей Юрьевич',
    company: 'ГБУЗ РБ ГКБ № 21 Г. УФА',
    phone: '8 (999) 444-89-03',
    position: 'Гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'otro227@mail.ru',
    visitsPlanned: 4,
    visitsPerformed: 1,
  },
  {
    id: v1(),
    fullName: 'Кузнецов Дмитрий Викторович',
    company: 'ГБУЗ РКБ ИМ. Г.Г.КУВАТОВА',
    phone: '8 (999) 336-41-25',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'shahmatka1990@mail.ru',
    visitsPlanned: 2,
    visitsPerformed: 1,
  },
  {
    id: v1(),
    fullName: 'Ледяхов Игорь Анатольевич',
    company: 'МУП ХП Г. УФЫ',
    phone: '8 (999) 156-39-93',
    position: 'Гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'g-bik@list.ru',
    visitsPlanned: 6,
    visitsPerformed: 4,
  },
  {
    id: v1(),
    fullName: 'Мамедов Рамиз Михманович',
    company: 'СПБ ГКУЗ',
    phone: '8 (999) 268-96-45',
    position: 'Гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Санкт-Петербург',
    email: 'nasoge@mail.ru',
    visitsPlanned: 5,
    visitsPerformed: 3,
  },
  {
    id: v1(),
    fullName: 'Миранчук Алексей Андреевич',
    company: 'ГБУЗ РБ ПОЛИКЛИНИКА № 46 Г.УФА',
    phone: '8 (999) 492-83-08',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'bagdasaryan1988@mail.ru',
    visitsPlanned: 5,
    visitsPerformed: 3,
  },
  {
    id: v1(),
    fullName: 'Подпалый Сергей Иванович',
    company: 'МЦ АРМЕД',
    phone: '8 (999) 442-99-45',
    position: 'Отоларингология',
    type: OrganizationTypes.PHARMACY,
    address: 'Сочи',
    email: 'mywaydao@rambler.ru',
    visitsPlanned: 4,
    visitsPerformed: 3,
  },
];

export const newTargetsPageDate: IFakeTarget[] = [
  {
    id: v1(),
    fullName: 'Яновский Игорь Сергеевич',
    company: 'ГБУЗ РКПЦ МЗ РБ',
    phone: '8 (999) 049-20-67',
    position: 'Ультразвуковая диагностика',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'lubov851@mail.ru',
    visitsPlanned: 4,
    visitsPerformed: 3,
  },
  {
    id: v1(),
    fullName: 'Шишкин Роман Александрович',
    company: 'ГБУЗ РБ РД № 3 Г.УФА',
    phone: '8 (999) 914-52-29',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'shayakhmetoff.artur@yandex.ru',
    visitsPlanned: 6,
    visitsPerformed: 3,
  },
  {
    id: v1(),
    fullName: 'Чугайнов Игорь Валерьевич',
    company: 'ГБУЗ РБ РД № 3 Г.УФА',
    phone: '8 (999) 760-63-26',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'mans.lily@yandex.ru',
    visitsPlanned: 4,
    visitsPerformed: 2,
  },
  {
    id: v1(),
    fullName: 'Чернышов Андрей Алексеевич',
    company: 'ООО "ИНС ОКБМ"',
    phone: '8 (999) 420-99-25',
    position: 'Гематология',
    type: OrganizationTypes.PHARMACY,
    address: 'Воронеж',
    email: 'uriimaltsev@mail.ru',
    visitsPlanned: 3,
    visitsPerformed: 2,
  },
  {
    id: v1(),
    fullName: 'Хохлов Дмитрий Валерьевич',
    company: 'КГБУЗ "БОГОТОЛЬСКАЯ МБ"',
    phone: '8 (999) 592-13-78',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Боготол',
    email: 'arisa275@yandex.ru',
    visitsPlanned: 7,
    visitsPerformed: 3,
  },
  {
    id: v1(),
    fullName: 'Федьков Андрей Юрьевич',
    company: 'Альфа центр Здоровья',
    phone: '8 (999) 492-33-24',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Тюмень',
    email: 'nadyusha@live.rubykolaki',
    visitsPlanned: 8,
    visitsPerformed: 3,
  },
  {
    id: v1(),
    fullName: 'Тетрадзе Омари Михайлович',
    company: 'ГБУЗ РБ ГКБ № 21 Г. УФА',
    phone: '8 (999) 437-69-40',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'gerbveronika@gmail.com',
    visitsPlanned: 2,
    visitsPerformed: 1,
  },
  {
    id: v1(),
    fullName: 'Сычёв Дмитрий Евгеньевич',
    company: 'ГБУЗ РБ ГКБ № 21 Г. УФА',
    phone: '8 (999) 444-89-03',
    position: 'Гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'otro227@mail.ru',
    visitsPlanned: 6,
    visitsPerformed: 4,
  },
  {
    id: v1(),
    fullName: 'Сергеев Олег Вячеславович',
    company: 'ГБУЗ РКБ ИМ. Г.Г.КУВАТОВА',
    phone: '8 (999) 336-41-25',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'shahmatka1990@mail.ru',
    visitsPlanned: 5,
    visitsPerformed: 4,
  },
  {
    id: v1(),
    fullName: 'Ребров Артём Геннадьевич',
    company: 'МУП ХП Г. УФЫ',
    phone: '8 (999) 156-39-93',
    position: 'Гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'g-bik@list.ru',
    visitsPlanned: 3,
    visitsPerformed: 2,
  },
  {
    id: v1(),
    fullName: 'Рауш Константин Викторович',
    company: 'СПБ ГКУЗ',
    phone: '8 (999) 268-96-45',
    position: 'Гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Санкт-Петербург',
    email: 'nasoge@mail.ru',
    visitsPlanned: 7,
    visitsPerformed: 4,
  },
  {
    id: v1(),
    fullName: 'Попов Денис Александрович',
    company: 'ГБУЗ РБ ПОЛИКЛИНИКА № 46 Г.УФА',
    phone: '8 (999) 492-83-08',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'bagdasaryan1988@mail.ru',
    visitsPlanned: 8,
    visitsPerformed: 4,
  },
  {
    id: v1(),
    fullName: 'Полоз Дмитрий Дмитриевич',
    company: 'МЦ АРМЕД',
    phone: '8 (999) 442-99-45',
    position: 'Отоларингология',
    type: OrganizationTypes.PHARMACY,
    address: 'Сочи',
    email: 'mywaydao@rambler.ru',
    visitsPlanned: 7,
    visitsPerformed: 3,
  },
];

export const falseTargetPlaned: IFakeTarget[] = [
  {
    id: v1(),
    fullName: 'Яновский Игорь Сергеевич',
    company: 'ГБУЗ РКПЦ МЗ РБ',
    phone: '8 (999) 049-20-67',
    position: 'Ультразвуковая диагностика',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'lubov851@mail.ru',
    visitsPlanned: 4,
    visitsPerformed: 3,
  },
  {
    id: v1(),
    fullName: 'Шишкин Роман Александрович',
    company: 'ГБУЗ РБ РД № 3 Г.УФА',
    phone: '8 (999) 914-52-29',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'shayakhmetoff.artur@yandex.ru',
    visitsPlanned: 6,
    visitsPerformed: 3,
  },
  {
    id: v1(),
    fullName: 'Чугайнов Игорь Валерьевич',
    company: 'ГБУЗ РБ РД № 3 Г.УФА',
    phone: '8 (999) 760-63-26',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'mans.lily@yandex.ru',
    visitsPlanned: 4,
    visitsPerformed: 2,
  },
  {
    id: v1(),
    fullName: 'Чернышов Андрей Алексеевич',
    company: 'ООО "ИНС ОКБМ"',
    phone: '8 (999) 420-99-25',
    position: 'Гематология',
    type: OrganizationTypes.PHARMACY,
    address: 'Воронеж',
    email: 'uriimaltsev@mail.ru',
    visitsPlanned: 3,
    visitsPerformed: 2,
  },
  {
    id: v1(),
    fullName: 'Хохлов Дмитрий Валерьевич',
    company: 'КГБУЗ "БОГОТОЛЬСКАЯ МБ"',
    phone: '8 (999) 592-13-78',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Боготол',
    email: 'arisa275@yandex.ru',
    visitsPlanned: 7,
    visitsPerformed: 3,
  },
  {
    id: v1(),
    fullName: 'Федьков Андрей Юрьевич',
    company: 'Альфа центр Здоровья',
    phone: '8 (999) 492-33-24',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Тюмень',
    email: 'nadyusha@live.rubykolaki',
    visitsPlanned: 8,
    visitsPerformed: 3,
  },
  {
    id: v1(),
    fullName: 'Тетрадзе Омари Михайлович',
    company: 'ГБУЗ РБ ГКБ № 21 Г. УФА',
    phone: '8 (999) 437-69-40',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'gerbveronika@gmail.com',
    visitsPlanned: 2,
    visitsPerformed: 1,
  },
  {
    id: v1(),
    fullName: 'Сычёв Дмитрий Евгеньевич',
    company: 'ГБУЗ РБ ГКБ № 21 Г. УФА',
    phone: '8 (999) 444-89-03',
    position: 'Гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'otro227@mail.ru',
    visitsPlanned: 6,
    visitsPerformed: 4,
  },
  {
    id: v1(),
    fullName: 'Сергеев Олег Вячеславович',
    company: 'ГБУЗ РКБ ИМ. Г.Г.КУВАТОВА',
    phone: '8 (999) 336-41-25',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'shahmatka1990@mail.ru',
    visitsPlanned: 5,
    visitsPerformed: 4,
  },
  {
    id: v1(),
    fullName: 'Ребров Артём Геннадьевич',
    company: 'МУП ХП Г. УФЫ',
    phone: '8 (999) 156-39-93',
    position: 'Гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'g-bik@list.ru',
    visitsPlanned: 3,
    visitsPerformed: 2,
  },
  {
    id: v1(),
    fullName: 'Рауш Константин Викторович',
    company: 'СПБ ГКУЗ',
    phone: '8 (999) 268-96-45',
    position: 'Гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Санкт-Петербург',
    email: 'nasoge@mail.ru',
    visitsPlanned: 7,
    visitsPerformed: 4,
  },
];

export const falseTargetCompleted: IFakeTarget[] = [
  {
    id: v1(),
    fullName: 'Чичерин Георгий Васильевич',
    company: 'ГБУЗ РКПЦ МЗ РБ',
    phone: '8 (999) 049-20-67',
    position: 'Ультразвуковая диагностика',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'lubov851@mail.ru',
    visitsPlanned: 4,
    visitsPerformed: 4,
  },
  {
    id: v1(),
    fullName: 'Литвинов Максим Максимович',
    company: 'ГБУЗ РБ РД № 3 Г.УФА',
    phone: '8 (999) 914-52-29',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'shayakhmetoff.artur@yandex.ru',
    visitsPlanned: 4,
    visitsPerformed: 4,
  },
  {
    id: v1(),
    fullName: 'Молотов Вячеслав Михайлович',
    company: 'ГБУЗ РБ РД № 3 Г.УФА',
    phone: '8 (999) 760-63-26',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'mans.lily@yandex.ru',
    visitsPlanned: 4,
    visitsPerformed: 4,
  },
  {
    id: v1(),
    fullName: 'Вышинский Андрей Януарьевич',
    company: 'ООО "ИНС ОКБМ"',
    phone: '8 (999) 420-99-25',
    position: 'Гематология',
    type: OrganizationTypes.PHARMACY,
    address: 'Воронеж',
    email: 'uriimaltsev@mail.ru',
    visitsPlanned: 3,
    visitsPerformed: 3,
  },
  {
    id: v1(),
    fullName: 'Молотов Вячеслав Михайлович',
    company: 'КГБУЗ "БОГОТОЛЬСКАЯ МБ"',
    phone: '8 (999) 592-13-78',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Боготол',
    email: 'arisa275@yandex.ru',
    visitsPlanned: 7,
    visitsPerformed: 7,
  },
  {
    id: v1(),
    fullName: 'Шепилов Дмитрий Трофимович',
    company: 'Альфа центр Здоровья',
    phone: '8 (999) 492-33-24',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Тюмень',
    email: 'nadyusha@live.rubykolaki',
    visitsPlanned: 8,
    visitsPerformed: 8,
  },
  {
    id: v1(),
    fullName: 'Тетрадзе Омари Михайлович',
    company: 'ГБУЗ РБ ГКБ № 21 Г. УФА',
    phone: '8 (999) 437-69-40',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'gerbveronika@gmail.com',
    visitsPlanned: 2,
    visitsPerformed: 2,
  },
  {
    id: v1(),
    fullName: 'Громыко Андрей Андреевич',
    company: 'ГБУЗ РБ ГКБ № 21 Г. УФА',
    phone: '8 (999) 444-89-03',
    position: 'Гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'otro227@mail.ru',
    visitsPlanned: 6,
    visitsPerformed: 6,
  },
  {
    id: v1(),
    fullName: 'Шеварднадзе Эдуард Амвросиевич',
    company: 'ГБУЗ РКБ ИМ. Г.Г.КУВАТОВА',
    phone: '8 (999) 336-41-25',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'shahmatka1990@mail.ru',
    visitsPlanned: 5,
    visitsPerformed: 5,
  },
  {
    id: v1(),
    fullName: 'Бессмертных Александр Александрович',
    company: 'МУП ХП Г. УФЫ',
    phone: '8 (999) 156-39-93',
    position: 'Гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'g-bik@list.ru',
    visitsPlanned: 3,
    visitsPerformed: 3,
  },
  {
    id: v1(),
    fullName: 'Панкин Борис Дмитриевич',
    company: 'СПБ ГКУЗ',
    phone: '8 (999) 268-96-45',
    position: 'Гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Санкт-Петербург',
    email: 'nasoge@mail.ru',
    visitsPlanned: 7,
    visitsPerformed: 7,
  },
];

export const falseTargetNotCompleted: IFakeTarget[] = [
  {
    id: v1(),
    fullName: 'Кочубей Виктор Павлович',
    company: 'ГБУЗ РКПЦ МЗ РБ',
    phone: '8 (999) 049-20-67',
    position: 'Ультразвуковая диагностика',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'lubov851@mail.ru',
    visitsPlanned: 5,
    visitsPerformed: 4,
  },
  {
    id: v1(),
    fullName: 'Куракин Алексей Борисович',
    company: 'ГБУЗ РБ РД № 3 Г.УФА',
    phone: '8 (999) 914-52-29',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'shayakhmetoff.artur@yandex.ru',
    visitsPlanned: 4,
    visitsPerformed: 1,
  },
  {
    id: v1(),
    fullName: 'Козодавлев Осип Петрович',
    company: 'ГБУЗ РБ РД № 3 Г.УФА',
    phone: '8 (999) 760-63-26',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.MPI,
    address: 'Уфа',
    email: 'mans.lily@yandex.ru',
    visitsPlanned: 4,
    visitsPerformed: 3,
  },
  {
    id: v1(),
    fullName: 'Голицын Александр Николаевич',
    company: 'ООО "ИНС ОКБМ"',
    phone: '8 (999) 420-99-25',
    position: 'Гематология',
    type: OrganizationTypes.PHARMACY,
    address: 'Воронеж',
    email: 'uriimaltsev@mail.ru',
    visitsPlanned: 4,
    visitsPerformed: 3,
  },
  {
    id: v1(),
    fullName: 'Ланской Василий Сергеевич',
    company: 'КГБУЗ "БОГОТОЛЬСКАЯ МБ"',
    phone: '8 (999) 592-13-78',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Боготол',
    email: 'arisa275@yandex.ru',
    visitsPlanned: 7,
    visitsPerformed: 3,
  },
  {
    id: v1(),
    fullName: 'Блудов Дмитрий Николаевич',
    company: 'Альфа центр Здоровья',
    phone: '8 (999) 492-33-24',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Тюмень',
    email: 'nadyusha@live.rubykolaki',
    visitsPlanned: 5,
    visitsPerformed: 3,
  },
  {
    id: v1(),
    fullName: 'Перовский Лев Алексеевич',
    company: 'ГБУЗ РБ ГКБ № 21 Г. УФА',
    phone: '8 (999) 437-69-40',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'gerbveronika@gmail.com',
    visitsPlanned: 3,
    visitsPerformed: 2,
  },
  {
    id: v1(),
    fullName: 'Валуев Пётр Александрович',
    company: 'ГБУЗ РБ ГКБ № 21 Г. УФА',
    phone: '8 (999) 444-89-03',
    position: 'Гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'otro227@mail.ru',
    visitsPlanned: 4,
    visitsPerformed: 1,
  },
  {
    id: v1(),
    fullName: 'Маков Лев Саввич',
    company: 'ГБУЗ РКБ ИМ. Г.Г.КУВАТОВА',
    phone: '8 (999) 336-41-25',
    position: 'Акушерство-гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'shahmatka1990@mail.ru',
    visitsPlanned: 4,
    visitsPerformed: 2,
  },
  {
    id: v1(),
    fullName: 'Игнатьев Николай Павлович',
    company: 'МУП ХП Г. УФЫ',
    phone: '8 (999) 156-39-93',
    position: 'Гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Уфа',
    email: 'g-bik@list.ru',
    visitsPlanned: 3,
    visitsPerformed: 1,
  },
  {
    id: v1(),
    fullName: 'Сипягин Дмитрий Сергеевич',
    company: 'СПБ ГКУЗ',
    phone: '8 (999) 268-96-45',
    position: 'Гинекология',
    type: OrganizationTypes.PHARMACY,
    address: 'Санкт-Петербург',
    email: 'nasoge@mail.ru',
    visitsPlanned: 3,
    visitsPerformed: 2,
  },
];

export const visitingChartData: IVisitingChartData[] = [
  {
    id: v1(),
    date: '',
    responsible: '',
    medicine: 'Элизария',
    potential: '5',
    loyalty: '4',
    objections: '',
    detailing: true,
  },
  {
    id: v1(),
    date: '',
    responsible: '',
    medicine: 'Тигераза',
    potential: '6',
    loyalty: '4',
    objections: '',
    detailing: true,
  },
  {
    id: v1(),
    date: '',
    responsible: '',
    medicine: 'Глуразим',
    potential: '5',
    loyalty: '3',
    objections: '',
    detailing: true,
  },
  {
    id: v1(),
    date: '',
    responsible: '',
    medicine: 'Элизария',
    potential: '4',
    loyalty: '2',
    objections: '',
    detailing: true,
  },
];

export const drugsData: IDrug[] = [
  {
    id: v1(),
    drug: 'Элизария',
  },
  {
    id: v1(),
    drug: 'Тигераза',
  },
  {
    id: v1(),
    drug: 'Глуразим',
  },
  {
    id: v1(),
    drug: 'Ибупрофен',
  },
  {
    id: v1(),
    drug: 'Дигоксин',
  },
  {
    id: v1(),
    drug: 'Глибенкламид',
  },
  {
    id: v1(),
    drug: 'Амиодарон',
  },
  {
    id: v1(),
    drug: 'Каптоприл',
  },
  {
    id: v1(),
    drug: 'Глимепирид',
  },
  {
    id: v1(),
    drug: 'Инсулин гларгин',
  },
  {
    id: v1(),
    drug: 'Фамотидин',
  },
  {
    id: v1(),
    drug: 'Бисопролол',
  },
  {
    id: v1(),
    drug: 'Нифедипин',
  },
  {
    id: v1(),
    drug: 'Глимепирид',
  },
  {
    id: v1(),
    drug: 'Омепразол',
  },
];

export const visitDescriptionCards: IVisitDescriptionCard[] = [
  {
    id: v1(),
    number: 1,
    date: dayjs(new Date()).subtract(7, 'week').toDate(),
    title:
      'Визит прошел неудачно, врач холодно отнёсся к препарату, малая вероятность выписки препаратов',
  },
  {
    id: v1(),
    number: 2,
    date: dayjs(new Date()).subtract(5, 'week').toDate(),
    title:
      'Визит прошел хорошо, врач лоялен к препарату, средняя вероятность выписки препаратов',
  },
  {
    id: v1(),
    number: 3,
    date: dayjs(new Date()).subtract(3, 'week').toDate(),
    title:
      'Визит прошел успешно, врач лоялен к препарату, высокая вероятность выписки препаратов',
  },
  {
    id: v1(),
    number: 4,
    date: dayjs(new Date()).subtract(12, 'day').toDate(),
    title:
      'Визит прошел успешно, врач лоялен к препарату, высокая вероятность выписки препаратов',
  },
  {
    id: v1(),
    number: 5,
    date: dayjs(new Date()).subtract(3, 'day').toDate(),
    title:
      'Визит прошел успешно, врач лоялен к препарату, высокая вероятность выписки препаратов',
  },
];
