export enum DateFormats {
  DATE_FORMAT = 'DD.MM.YYYY',
  DATE_FORMAT_FOR_COMPARE = 'DD:MM:YYYY',
  VISIT_DATE_FORMAT = 'DD:MM:YYYY',
  APP_DATE_FORMAT = 'DD.MM.YYYY',
  VISIT_REPORT_DATE_FORMAT = 'HH:mm:ss',
  TIME_FORMAT = 'HH:mm',
  EVENT_DATE_FORMAT = 'DD MM YYYY  HH:mm',
  TASK_DATE_FORMAT = 'DD.MM.YYYY, HH:mm',
  FULL_DATE_FORMAT = 'DD.MM.YYYY HH:mm',
}
